name: Build Borderless Gaming Online

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Release executable
      run: msbuild BorderlessGaming.sln /p:Configuration=Release

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: BorderlessGaming-Executable
        path: BorderlessGaming/bin/Release/
